### ISSUE TITLE
Support strings coercion in scope

### ISSUE THREAD

**Issue by am-kantox** [narrowtux/abacus#10]
```elixir
iex(1)> Abacus.eval "a>5", %{"a" => 4.5}
{:ok, false}
iex(2)> Abacus.eval "a>5", %{"a" => "4.5"}
{:ok, true}
```

Of course, I can do a coercion to respective `Float` before `eval`ing, but people expect this to be done by abacus :)

I believe, the coercion might be easily done [here](https://github.com/narrowtux/abacus/blob/master/lib/eval.ex#L103). Please confirm, and I will provide the pull request.
Thanks in advance.

**Comment by narrowtux** [comment]
I'm not sure if that would be in scope of the library, it feels like fuzzy behaviour to me. 

Also, this can bite me if I decide to implement some string support later.

**Comment by am-kantox** [comment]
Fair enough. Please don’t hesitate to close this issue, you’re absolutely right, this is out of scope.

Sorry for bringing this out.

**Comment by narrowtux** [comment]
Don't feel bad about it :)
