### ISSUE TITLE
Accept `.2` and `2.` as floats

### ISSUE THREAD

**Issue by am-kantox** [narrowtux/abacus#11]
Currently the formula’s parser fails with:

``` elixir
{:error, {1, :math_term_parser, ['syntax error before: ', '\'.\'']}}
```

on floats with omitted leading/trailing zero (`.25` / `2.`.) It is quite common to have floats being written that way, so I would suggest it makes sense to accept this notation.

**Comment by narrowtux** [comment]
fixed with https://github.com/narrowtux/abacus/commit/0f58c68e8cf639fe9b3077d25e7abac580649451#diff-1bf48c3e78695d2c64a7fe61c41c5e7cL3
